### ISSUE TITLE
Minecord Bot Error on player join

### ISSUE THREAD

**Issue by TheTechnologyStudio** [CyR1en/Minecordbot#76]
Version: Paperspigot 1.8.8
Error: https://hastebin.com/ifamahejuw.vbs

**Comment by TheFlagCourier** [comment]
Thank you @GameHoundInteractive  for taking your time to submit the issue. In the future, please refrain from adding a "Priority" tag to your issue titles. Marking as duplicate of #61. 

The fix for this issue is currently in testing, and is available in the [MineCordBot 2.2.1 Beta releases](https://github.com/CyR1en/Minecordbot/releases/tag/v2.2.1-beta2)
